Gophermart
aykuli/loystem pull request #4
Opened 2024-06-26 21:02 UTC by aykuli

2024-07-02 21:34 UTC, avhitrov requested changes
Архитектурно решение хорошее и верное, но есть много частных замечаний по реализации. Я не стал писать замечания к каждому случаю не вполне верного использования тех или иных конструкций, особенно в использовании транзакций, так что, если замечание есть, необходимо посмотреть на все возможные аналогичные ошибки в коде.

А так - все вполне правится без переделки основной схемы работы.

2024-07-02 21:34 UTC, avhitrov commented on pkg/postgres/order.go
> +	foundOrder, err := ordersRepo.FindByNumber(ctx, tx, number)
Ради одного запроса вообще нет смысла открывать транзакцию. А ради SELECT нет смысла открывать транзакцию в частности. Чтобы заблокировать запись или набор записей на SELECT, необходимо использоваться SELECT FOR UPDATE. И только в том случае, если эти записи участвуют в последующем обновлении и косвенно связаны с этим последующим обновлением.

2024-07-05 14:53 UTC, aykuli commented on cmd/gophermart/main.go
> +		signal.Notify(appShutdownCh, os.Interrupt)
![Screenshot from 2024-07-05 21-52-44](https://github.com/aykuli/loystem/assets/49780822/da075f3a-6865-4500-b61b-ca59d0323fdf)

2024-07-09 22:34 UTC, avhitrov approved these changes
Есть несколько замечаний, касающихся в первую очередь устойчивости кода (и одна забытая отладка). По сути и количеству они не являются стопперами для приемки проекта, но, надеюсь, твой перфекционизм не позволит им остаться неисправленными. Аппрув!

2024-07-09 22:34 UTC, avhitrov commented on internal/agent/agent.go
> +	}
Выше находится switch с вариантом выхода из данной функции. Соответственно, в этом случае тело ответа останется незакрытым и ресурсы будут утекать. Стоит поставить закрытие в виде `defer resp.Body.Close()` сразу после проверки ошибки Get.

2024-07-09 22:34 UTC, avhitrov commented on internal/agent/agent.go
> +		p.GetOneOrderInfo(ctx, o, retryCount+1)
При многократном ответе 500 от черного ящика рискуем сожрать буфер вызовов большим количеством рекурсий. Здесь стоит так же проверять количество сделанных ретраев и выходить по их достижению. Либо вообще проверку на ретраи вынести в начало функции.

2024-07-09 22:34 UTC, avhitrov commented on pkg/postgres/order.go
> +	fmt.Println("1")
```suggestion
```

2025-01-10 11:54 UTC, merged